routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(["register"=>false]);

Route::get('/reviews', 'ReviewsController@index');

Route::post('/reviews', 'ReviewsController@store');

Route::group([
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth']
],function()
{
    Route::get("admin",'HomeController@index')->name('home');

    Route::resource("admin/reviews","ReviewsController");
});

app/Models/Review.php
<?php

namespace App\Models;

use App\Http\Requests\Reviews\UpdateRequest;
use App\Models\Traits\CanBeFiltered;
use App\Models\Traits\CanBeOrdered;
use App\Models\Traits\DateFormat;
use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    use DateFormat;
    use CanBeFiltered;
    use CanBeOrdered;

    protected $fillable = ['name','email','message','status','edited','notify','image'];

    public static $defaultPhoto = '/storage/reviews/no-photo.png';

    public const STATUS_NEW = 'new';
    public const STATUS_ACCEPT = 'accept';
    public const STATUS_REJECT = 'reject';

    public static function statusList(): array
    {
        return [
            self::STATUS_NEW => 'Новый',
            self::STATUS_ACCEPT => 'Принят',
            self::STATUS_REJECT => 'Отклонен',
        ];
    }

    public function getDefaultPhotoAttribute()
    {
        return static::$defaultPhoto;
    }

    public function isEditedByAdmin(Review $old,UpdateRequest $new)
    {
        $compare = [
            'name',
            'message',
            'email'
        ];

        foreach($compare as $field)
        {
            if($old->{$field} !== $new->{$field})
            {
                return true;
            }
        }

        return false;
    }
}

app/Models/Traits/CanBeFiltered.php
<?php

namespace App\Models\Traits;

use App\Contracts\ModelFilter\ModelFilterScoper;
use Illuminate\Database\Eloquent\Builder;

trait CanBeFiltered
{
    public function scopeWithFilters(Builder $builder,$scopes = [])
    {
        $scoper = new ModelFilterScoper(request());

        $scoper->apply($builder, $scopes);
    }
}

app/Models/Traits/CanBeOrdered.php
<?php

namespace App\Models\Traits;

use App\Contracts\ModelOrder\ModelOrderScoper;
use Illuminate\Database\Eloquent\Builder;

trait CanBeOrdered
{
    public function scopeWithOrders(Builder $builder,$orders = [])
    {
        $scoper = new ModelOrderScoper(request());

        $scoper->apply($builder, $orders);
    }
}

app/Models/Traits/DateFormat.php
<?php

namespace App\Models\Traits;

trait DateFormat
{
    public function getFormatCreatedAtAttribute()
    {
        if(isset($this->created_at))
        {
            return \Carbon\Carbon::parse($this->created_at)->format('d.m.Y H:i:s');
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('admin.home');
    }
}

app/Http/Controllers/Admin/ReviewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contracts\ModelFilter\Filters\Review\FindCreatedAtFrom;
use App\Contracts\ModelFilter\Filters\Review\FindCreatedAtTo;
use App\Contracts\ModelFilter\Filters\Review\FindEmail;
use App\Contracts\ModelFilter\Filters\Review\FindName;
use App\Contracts\ModelOrder\Orders\Review\OrderByCreatedAt;
use App\Contracts\ModelOrder\Orders\Review\OrderByEmail;
use App\Contracts\ModelOrder\Orders\Review\OrderByName;
use App\Helpers\Admin\Review\OrderDirectionHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Reviews\UpdateRequest;
use App\Models\Review;

class ReviewsController extends Controller
{
    public function index(OrderDirectionHelper $orderHelper)
    {
        $reviews = Review::withOrders($this->orders())
            ->withFilters($this->filters())
            ->paginate(20)
            ->appends(request()->all());

        $statusList = Review::statusList();

        return view('admin.reviews.index', compact('reviews','orderHelper','statusList'));
    }

    public function show(Review $review)
    {
        $statusList = Review::statusList();

        return view('admin.reviews.show',compact('review','statusList'));
    }

    public function edit(Review $review)
    {
        $statusList = Review::statusList();

        if($review->status !== Review::STATUS_NEW)
        {
            unset($statusList[Review::STATUS_NEW]);
        }

        return view('admin.reviews.edit',compact('review','statusList'));
    }

    public function update(UpdateRequest $request, Review $review)
    {
        $data = [
            'name' => $request['name'],
            'email' => $request['email'],
            'message' => $request['message'],
            'status' => $request['status'],
        ];

        if($review->isEditedByAdmin($review,$request))
        {
            $data['edited'] = true;
        }

        $review->update($data);

        return redirect()->route('admin.reviews.show',compact('review'));
    }

    public function filters()
    {
        return array(
            'find_created_at_from' => new FindCreatedAtFrom(),
            'find_created_at_to' => new FindCreatedAtTo(),
            'find_email' => new FindEmail(),
            'find_name' => new FindName()
        );
    }

    public function orders()
    {
        return array(
            'created_at' => new OrderByCreatedAt(),
            'name' => new OrderByName(),
            'email' => new OrderByEmail()
        );
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReviewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Reviews\CreateRequest;
use App\Jobs\Review\TelegramNotifyJob;
use App\Models\Review;
use Intervention\Image\Constraint;
use Intervention\Image\Facades\Image;

class ReviewsController extends Controller
{
    public function index()
    {
        $reviews = Review::orderBy('created_at','desc')
            ->where('status', '=', Review::STATUS_ACCEPT)
            ->paginate(5);

        $defaultPhoto = Review::$defaultPhoto;

        return view('reviews.index',compact('reviews','defaultPhoto'));
    }

    public function store(CreateRequest $request)
    {
        $data = $request->only([
            'name',
            'email',
            'message',
        ]);

        $data['status'] = Review::STATUS_NEW;

        $review = Review::create($data);

        if($request->hasFile('image'))
        {
            $file = $request->file('image');

            $image = Image::make($file->getRealPath());
            $image->resize(320, 240,function (Constraint $constraint)
            {
                $constraint->aspectRatio();
            });

            $fileName = sprintf('%s.%s',$review->id, $file->getClientOriginalExtension());

            $image->save(
                public_path('storage/reviews/'.$fileName)
            );

            $image->destroy();

            $review->image = '/storage/reviews/'. $fileName;
        }
        else
        {
            $review->image = Review::$defaultPhoto;
        }

        $review->save();

        $job = (new TelegramNotifyJob($review->id))->delay(5);

        $this->dispatch($job);

        return ['success' => true];
    }
}

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/reviews/edit.blade.php
@extends('layouts.admin')

@section('content')

    <form method="POST" action="{{ route('admin.reviews.update', $review) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Имя пользователя</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $review->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">Email</label>
            <input id="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{old('email', $review->email) }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="message" class="col-form-label">Сообщение</label>
            <input id="message" class="form-control{{ $errors->has('message') ? ' is-invalid' : '' }}" name="message" value="{{old('message', $review->message) }}" required>
            @if ($errors->has('message'))
                <span class="invalid-feedback"><strong>{{ $errors->first('message') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="status" class="col-form-label">Статус</label>
            <select id="status" class="form-control" name="status">
                @foreach ($statusList as $value => $label)
                    <option value="{{ $value }}"{{ $value === old('status', $review->status) ? ' selected' : '' }}>{{ $label }}</option>
                @endforeach;
            </select>

            @if ($errors->has('status'))
                <div class="alert alert-danger mt-3"><strong>{{ $errors->first('status') }}</strong></div>
            @endif

        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/reviews/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card mb-3">
        <div class="card-header">Фильтр</div>
        <div class="card-body">
            <form action="?" method="GET">
                <input type="hidden" name="order_by" value="{{ request('order_by') }}">
                <input type="hidden" name="direction" value="{{ request('direction') }}">
                <input type="hidden" name="page" value="{{ request('page') }}">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Имя пользователя</label>
                            <input id="name" class="form-control" name="find_name" value="{{ request('find_name') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="email" class="col-form-label">Email</label>
                            <input id="email" class="form-control" name="find_email" value="{{ request('find_email') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="datetime_created_at_from" class="col-form-label">Дата создания от</label>
                            <date-input-component :name="'find_created_at_from'" value="{{ request('find_created_at_from')}}"></date-input-component>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="datetime_created_at_to" class="col-form-label">Дата создания до</label>
                            <date-input-component :name="'find_created_at_to'" value="{{ request('find_created_at_to') }}"></date-input-component>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br />
                            <button type="submit" class="btn btn-primary mr-3">Найти</button>
                            <button type="reset" class="btn btn-primary">Очистить</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            Найдено записей: {{$reviews->total()}}
        </div>
    </div>

    <table class="table table-bordered table-striped table-responsive-sm">
        <thead>
            <tr>
                <th>ID</th>
                <th>Фото</th>
                <th>
                    <a href="{{route('admin.reviews.index',$orderHelper->makeRequest("name"))}}">
                        Имя пользователя
                        @if($orderHelper->isCurrentOrder('name') && $orderHelper->isDescDirection())
                            <i class="fa fa-angle-down"></i>
                        @else
                            <i class="fa fa-angle-up"></i>
                        @endif
                    </a>
                </th>
                <th>
                    <a href="{{route('admin.reviews.index',$orderHelper->makeRequest("email"))}}">
                        Email
                        @if($orderHelper->isCurrentOrder('email') && $orderHelper->isDescDirection())
                            <i class="fa fa-angle-down"></i>
                        @else
                            <i class="fa fa-angle-up"></i>
                        @endif
                    </a>
                </th>
                <th>Сообщение</th>
                <th>Статус</th>
                <th>
                    <a href="{{route('admin.reviews.index',$orderHelper->makeRequest("created_at"))}}">
                        Дата создания
                        @if($orderHelper->isCurrentOrder('created_at') && $orderHelper->isDescDirection())
                            <i class="fa fa-angle-down"></i>
                        @else
                            <i class="fa fa-angle-up"></i>
                        @endif
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>

        @foreach ($reviews as $review)
            <tr>
                <td>{{ $review->id }}</td>
                <td>
                    <div class="admin-image-handler">
                        <img class="admin-image" src="{{$review->image}}">
                    </div>
                </td>
                <td>
                    <a href="{{ route('admin.reviews.show', $review) }}">
                        {{ $review->name }}
                    </a>
                    @if($review->edited)
                        <div class="alert alert-primary mt-2" role="alert">
                            Изменен администратором
                        </div>
                    @endif
                </td>
                <td>{{ $review->email }}</td>
                <td>{{ $review->message }}</td>
                <td>
                    {{ $statusList[$review->status] }}
                </td>
                <td>{{ $review->format_created_at }}</td>
            </tr>
        @endforeach

        </tbody>
    </table>

    {{ $reviews->links() }}
@endsection

resources/views/admin/reviews/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.reviews.edit', $review) }}" class="btn btn-primary mr-1">Редактировать</a>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
            <tr class="row no-gutters">
                <th class="col-6 px-3">ID</th><th class="col-6 px-3">{{$review->id}}</th>
            </tr>
            <tr class="row no-gutters">
                <th class="col-6 px-3">Фото</th>
                <th class="col-6 px-3">
                    <img class="admin-image" src="{{$review->image}}">
                </th>
            </tr>
            <tr class="row no-gutters">
                <th class="col-6 px-3">Имя пользователя</th><th class="col-6 px-3">{{$review->name}}</th>
            </tr>
            <tr class="row no-gutters">
                <th class="col-6 px-3">Email</th><th class="col-6 px-3">{{$review->email}}</th>
            </tr>
            <tr class="row no-gutters">
                <th class="col-6 px-3">Сообщение</th><th class="col-6 px-3">{{$review->message}}</th>
            </tr>
            <tr class="row no-gutters">
                <th class="col-6 px-3">Статус</th><th class="col-6 px-3">{{$statusList[$review->status]}}</th>
            </tr>
        </tbody>
    </table>
@endsection

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li>
                        <a href="{{ route("admin.reviews.index") }}">Reviews</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('admin.home') }}">Admin</a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container">
            @yield('content')
        </div>
    </main>
</div>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/reviews/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <reviews-parent :items='@json($reviews)' :default-photo="'{{$defaultPhoto}}'">
                    <p slot="title">
                        Отзывы <span class="text-secondary">{{$reviews->total()}}</span>
                    </p>
                    <div slot="links">
                        {{ $reviews->links() }}
                    </div>
                </reviews-parent>
            </div>
        </div>
    </div>
@endsection